name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        shell: bash
        run: |
          pnpm install

      - name: Build
        shell: bash
        run: |
          pnpm build

      - name: Test
        shell: bash
        run: |
          pnpm test

      - name: Lint
        shell: bash
        run: |
          pnpm lint || true
