name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        run: git clone https://github.com/ActionpackdHQ/ai-sdk.git .
      - name: Setup
        run: |
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt-get install -y nodejs
          sudo npm install -g pnpm
      - name: Build and Test
        run: |
          pnpm install
          pnpm build
          pnpm test
